# Numpy


1.   **Library**: Numpy is a Python library for numerical computing.
2. **Arrays**: Core functionality revolves around multidimensional arrays
3. **Mathematical Functions**: Offers a wide range of mathematical functions for array operations.
4. **Efficiency:** Designed for efficiency in terms of both speed and memory usage
5. **Data Science:** Widely used in data science, machine learning, and scientific research for numerical computations.







**bold text**


# Installation

pip install numpy

Creation of ndarry and aliases

In [2]:
import numpy 
arr=numpy.array([1]) 
print(arr)

[1]


**2-D Array**

In [9]:
import numpy 
arr=numpy.array([[1,2,3],[4,5,6]]) 
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


**3-D Array**

In [10]:
import numpy 
arr=numpy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) 
print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [7]:
#zero array
import numpy as np 
arr=np.zeros((3,3))
print(arr)
print(type(arr))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


**Shape of an Array**

**Checking Dimensions**

**Using tuple to create arrays**

In [11]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


**Indexing of 1-D Array**

In [12]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28,29])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[-5])

1
5
29
4


**Indexing 2-D Array**

In [14]:
import numpy 
arr=numpy.array([[1,2,3,56,92,34],[4,5,6,95,29,29]]) 
print(arr[-1,4])

29


**Indexing 3-D Array**

In [16]:
import numpy 
arr=numpy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) 
print(arr[1,1,0])

4


**Negative Indexing**

**Slicing**
      
            0,1,2,3,4
           -5,-4,-3,-2,-1

In [21]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28,29])
print(arr[1:3]) #start:end+1:step print->start to end
print(arr[1:5])
print(arr[:3])
print(arr[2:])
print(arr[-4:-1])
print(arr[::2])

[22 34]
[22 34  4  5]
[ 1 22 34]
[34  4  5 67 28 29]
[ 5 67 28]
[ 1 34  5 28]


**Copying arrays**

In [26]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28,29])
x=arr.copy()#copy doesnt change 
print(x)
arr[0]=3
print(arr)
print(x)
x[0]=5
print(x)
print(arr)

[ 1 22 34  4  5 67 28 29]
[ 3 22 34  4  5 67 28 29]
[ 1 22 34  4  5 67 28 29]
[ 5 22 34  4  5 67 28 29]
[ 3 22 34  4  5 67 28 29]


**View Array**

In [28]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28,29])
x=arr.view()
print(x)
arr[0]=4
print(x)

[ 1 22 34  4  5 67 28 29]
[ 4 22 34  4  5 67 28 29]


**Join**

In [29]:
import numpy as np
arr1=np.array([1,22,34,4])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1 22 34  4  6  7  8  9 10]


**Split**

In [32]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28])
# newarr=np.array_split(arr,3)
# print(newarr)
newarr2=np.array_split(arr,4)
print(newarr2)

[array([ 1, 22]), array([34,  4]), array([ 5, 67]), array([28])]


**Datatype**

In [35]:
import numpy as np
# arr=np.array([1,22,34,4,5,67,28])
arr=np.array([1.0,3.0,4,5])
print(arr.dtype)

float64


**Iterating**

In [40]:
import numpy as np
arr=np.array([1,22,34,4,5,67,28])
for i in arr:
    print(i) 

1
22
34
4
5
67
28
